@{
    RootModule        = 'tismatic.pwsh.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '8efc31aa-24b9-4610-8123-42013af3ede4'
    Author            = 'Noah Peltier'
    Copyright         = '(c) Noah Peltier. All rights reserved.'
    Description       = 'PowerShell utilities and quality-of-life functions for Microsoft 365, Active Directory, and systems administration.'
    PowerShellVersion = '7.4'
    CompatiblePSEditions = @('Core')

    FunctionsToExport = @(
        'Add-MgGroupMember'
        'Add-MgUserDirectoryRole'
        'Add-MgUserLicense'
        'Add-ProxyAddress'
        'Block-UserSignin'
        'Clear-MgDeviceOwner'
        'Clear-MgUserOnPremImmutableId'
        'Compress-MgAppArtifact'
        'Connect-365Admin'
        'Convert-HtmlToPlainText'
        'ConvertFrom-EpochTime'
        'ConvertTo-EpochTime'
        'ConvertTo-HumanDuration'
        'ConvertTo-MgSamlNameIdClaim'
        'ConvertTo-MgSamlSourcedClaim'
        'ConvertTo-MgSamlValueClaim'
        'ConvertTo-PemCertificate'
        'Disconnect-365Admin'
        'Export-M365StorageWorkbook'
        'Find-ADuser'
        'Find-MGDevice'
        'Find-MgDeviceByUser'
        'Find-MgGroup'
        'Find-MgUser'
        'Find-User'
        'Format-Size'
        'Get-ADComputerBitLocker'
        'Get-ADPasswordExpirationReport'
        'Get-CimDiskStats'
        'Get-DomainFromDN'
        'Get-InstalledSoftware'
        'Get-MgDeviceOwnerReport'
        'Get-MgFilesSharedWithMe'
        'Get-MgFullGroupsReport'
        'Get-MgLicenseBreakdownPerDomain'
        'Get-MgLicenseSummary'
        'Get-MgOnPremObject'
        'Get-MgReport'
        'Get-MgSamlExistingApp'
        'Get-MgSamlSigningCertificate'
        'Get-MgSubscriptionReport'
        'Get-MgUserGroupReport'
        'Get-MgUserSigninLogs'
        'Get-MicrosoftOfficeProduct'
        'Get-MyUpn'
        'Get-NewPassword'
        'Get-PowerAutomateAuth'
        'Get-PowerAutomateFailedRun'
        'Get-StringSimilarity'
        'Get-TenantIDfromUserID'
        'Get-TrustedAdDomains'
        'Get-UserNinjaDevice'
        'Get-UserTypeName'
        'Import-LiquidTemplate'
        'Invoke-BlockUserSignin'
        'Lookup'
        'New-AmazonConnectApp'
        'New-DicePassphrase'
        'New-MgSamlApp'
        'New-PsCredential'
        'Remove-MgGroupMember'
        'Remove-MgUserDirectoryRole'
        'Remove-MgUserLicense'
        'Remove-ProxyAddress'
        'Reset-UserPassword'
        'Resolve-ADIdentity'
        'Restart-PowerAutomateRun'
        'Save-MgAppCertificate'
        'Save-MgAppFederationXml'
        'Select-SimilarObject'
        'Send-MgTeamsMessage'
        'Set-MgIntunePrimaryUser'
        'Set-MgSamlClaimsPolicy'
        'Set-MgUserOnPremImmutableId'
        'Set-PrimarySMTPAddress'
        'Show-Bar'
        'Test-MgIdentityConditionalAccess'
        'Test-PwnedPassword'
        'Update-MgDeviceOwner'
        'Write-LogMsg'
    )

    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()

    PrivateData = @{
        PSData = @{
            Tags       = @('PowerShell', 'Microsoft365', 'ActiveDirectory', 'Utilities')
            LicenseUri = 'https://github.com/tismatic/tismatic.pwsh/blob/main/LICENSE'
            ProjectUri = 'https://github.com/tismatic/tismatic.pwsh'
        }
    }
}
